### ISSUE TITLE
/v2/bars returning error for time frame 1Hour

### ISSUE THREAD

**Issue by SDiamante13** [alpacahq/Alpaca-API#178] opened 2021-04-13 05:32 UTC
**Describe the bug**
For /v2/bars the documentation says that 1Hour is a valid timeframe, however it returns an error.  

**To Reproduce**
1) Hit endpoint -
 https://data.alpaca.markets/v2/stocks/AAPL/bars?start=2021-04-12&end=2021-04-12&timeframe=1Hour

**Expected behavior**
Returns data for stock symbol

**Actual Behavior**
```json
{
    "code": 42210000,
    "message": "invalid timeframe"
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/29823897/114501377-81acb300-9bef-11eb-803c-0f5ab0b074cf.png)

**Comment by malpaca7** [comment] 2021-06-04 17:46
Hey @SDiamante13 -- Mallory from the Alpaca team here.

I'm unable to replicate this issue; can you try hitting this endpoint again and see if you're still getting that error message?

**Comment by gnvk** [comment] 2022-01-03 09:59
Hey 👋  I'm also unable to reproduce this issue and as such I will close it. If you're still experiencing this, please reopen and add more details.

**Closed as completed by gnvk** 2022-01-03 09:59 UTC
