### ISSUE TITLE
OAuth2 returns "invalid_client" error

### ISSUE THREAD

**Issue by lvca** [alpacahq/Alpaca-API#179] opened 2021-04-13 05:54 UTC
**Describe the bug**
OAuth request returns `{"code":40110000,"message":"invalid_client"}` in the last hours.

**Expected behavior**
A valid JSON with the token.

**Desktop (please complete the following information):**
 - OS: MacOSX
 - Browser Safari

**Additional context**
The client id used is unchanged for 1y. Checked on my account and it matches with the one passed.

**Comment by andylebo20** [comment] 2021-05-02 22:11
any update on this? getting same error

**Comment by captainsalt** [comment] 2021-05-09 00:26
I am also getting the same error

**Comment by umitanuki** [comment] 2021-05-09 05:53
The original question was resolved by adding `application/x-www-form-urlencoded` to the request header. This is per [RFC](https://tools.ietf.org/html/rfc6749#section-3.2)

If this is not the cause, please open a new issue with the details.

**Closed as completed by umitanuki** 2021-05-09 05:53 UTC

**Comment by mjKosmic** [comment] 2023-06-09 06:04
I am having this issue and i have set the header
