### ISSUE TITLE
Support multiple paper trading "accounts"

### ISSUE THREAD

**Issue by mtcliatt** [alpacahq/Alpaca-API#83] opened 2019-10-18 02:57 UTC
Having multiple "accounts" for paper trading would be incredibly useful for testing multiple strategies in real time.

**Comment by fsiler** [comment] 2020-06-27 04:24
Bump- any word on the possibility/timing of this feature?

**Comment by ZippeyKeys12** [comment] 2020-11-07 05:51
Duplicate of #35

**Closed by ZippeyKeys12** 2020-11-07 05:51 UTC
Labels: feature request
