### ISSUE TITLE
Data endpoint requests fail from browser (CORS)

### ISSUE THREAD

**Issue by ZBedjaJohnson** [alpacahq/Alpaca-API#152] opened 2021-01-05 04:32 UTC
When sending GET requests to **data.alpaca.markets** endpoints, the following CORS issue occurs:

_"Access to fetch at 'https://data.alpaca.markets/v1/last_quote/stocks/AMD' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."_

Checking the network logs, the browser sends a preflight OPTIONS request which doesn't send the authentication header ([by W3 spec](https://stackoverflow.com/a/15734032)), the data API currently rejects the request with status 403 (due to lack of authorization header) preventing the browser sending the actual GET request.

This doesn't occur with the **paper-api.alpaca.markets** or **api.alpaca.markets**, both send back a valid response to the OPTIONS preflight request, allowing the GET request to be sent afterwards with the authorization header.

A simple example:
```
fetch(`https://data.alpaca.markets/v1/last_quote/stocks/AMD`, { 
    headers: { 
      Authorization: 'Bearer (oAuth access_token here)' 
    } 
  })
```
Inspecting the response:
![image](https://user-images.githubusercontent.com/52133298/103605990-3c505980-4f0d-11eb-9bb7-4b93b7409a3f.png)

Expected a 200 response with correct 'Access-Control-Allow-Origin' headers as seen with a **paper-api.alpaca.markets** call:

![image](https://user-images.githubusercontent.com/52133298/103606080-7de10480-4f0d-11eb-8bf7-6c1ff6cf00b3.png)

Tested in both Chrome and Firefox:
 - OS: Windows 10
 - Browser Chrome
 - Version 87.0.4280.88 (Official Build) (64-bit)

 - OS: Windows 10
 - Browser Firefox
 - Version 84.0.1 (64-bit)

I checked the issue https://github.com/alpacahq/Alpaca-API/issues/100, however, this was due to a poor URL, hence a 404 (Not Found) error instead of the 403 (Forbidden) which shouldn't be returned to the preflight OPTIONS request from my knowledge.

To test a possible fix for the issue I injected the authorisation header into the OPTIONS request using the chrome addon ModHeader, which worked but goes against W3 Spec for preflight requests and isn't required with the non-data endpoints.

**Comment by kalmant** [comment] 2021-01-05 13:04
Thank you for the detailed report!

We were able to reproduce the problem and made the necessary adjustments.

Please verify if the issue is resolved so we can make further changes if necessary.

**Comment by ZBedjaJohnson** [comment] 2021-01-05 15:36
Thanks for the fast turnaround, I can verify it's working as intended in both my environments.

I see you return a 204 code for the data endpoint, which makes more sense to me,[ but some say it can cause issues in certain browsers](https://stackoverflow.com/a/58794243). Whatever decision you make, I'd update the **paper-api.alpaca.markets** and **api.alpaca.markets** for consistency as they currently return 200.

**Comment by kalmant** [comment] 2021-01-05 15:46
Thanks for the quick reply.

We tested it w/ Firefox 84.0.1 and lucikly there was no issue at all.
I can't promise when we'll be able to unify the response status codes but we'll keep it in mind.

I'm closing this issue since the problem was resolved.
Thanks once again for the report!

**Closed as completed by kalmant** 2021-01-05 15:46 UTC
